apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jm-backstage-product-service
  description: Service for managing products
  tags:
    - product
    - service
  annotations:
    github.com/project-slug: aquijun/jm-backstage-product-service
spec:
  type: service
  owner: team-ecommerce
  lifecycle: experimental
  repository: https://github.com/aquijun/jm-backstage-product-service.git
  providesApis:
    - product-api
  # dependsOn:
  #   - reosurce: postgres-db

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: product-api
  description: This is a sample API
  tags:
    - product
    - api
spec:
  type: openapi
  lifecycle: experimental
  owner: team-ecommerce
  definition: |
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths:
      /:
        get:
          summary: Sample endpoint
          responses:
            '200':
              description: Successful response
